project_name: xq
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - aix
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - ppc64
    goamd64:
      - ''
    ignore:
      - goos: linux
        goarch: ppc64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  filters:
    exclude:
      - '^TECH'
