// Code generated by "stringer -type ContentType"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContentXml-0]
	_ = x[ContentHtml-1]
	_ = x[ContentJson-2]
	_ = x[ContentText-3]
}

const _ContentType_name = "ContentXmlContentHtmlContentJsonContentText"

var _ContentType_index = [...]uint8{0, 10, 21, 32, 43}

func (i ContentType) String() string {
	if i < 0 || i >= ContentType(len(_ContentType_index)-1) {
		return "ContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentType_name[_ContentType_index[i]:_ContentType_index[i+1]]
}
