name: build

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'build.yml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23

      - name: Build
        run: go build

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
